"""학제간 AI 인사이트 시드 데이터 -- 검증된 원리-AI 매핑"""

PRINCIPLE_SEEDS = [
    # =========================================================================
    # 공학 > 제어공학 (control_engineering)  [4 seeds]
    # =========================================================================
    {
        "id": "ctrl_optimal_control",
        "discipline": "control_engineering",
        "discipline_name": "제어공학",
        "super_category": "공학",
        "principle_name": "Bellman Equation and Dynamic Programming",
        "principle_name_en": "Bellman Equation and Dynamic Programming",
        "ai_connection": "강화학습 가치 함수의 직접적 수학적 토대",
        "ai_connection_en": "Direct mathematical foundation of reinforcement learning value functions",
        "problem_solved": "순차적 의사결정에서 최적 정책의 수학적 도출",
    },
    {
        "id": "ctrl_kalman_filter",
        "discipline": "control_engineering",
        "discipline_name": "제어공학",
        "super_category": "공학",
        "principle_name": "Kalman Filter",
        "principle_name_en": "Kalman Filter",
        "ai_connection": "은닉 상태 추정, 센서 퓨전, 베이지안 필터링의 원류",
        "ai_connection_en": "Origin of hidden state estimation, sensor fusion, and Bayesian filtering in AI",
        "problem_solved": "잡음이 있는 관측에서 시스템의 실제 상태를 최적 추정",
    },
    {
        "id": "ctrl_pid_control",
        "discipline": "control_engineering",
        "discipline_name": "제어공학",
        "super_category": "공학",
        "principle_name": "PID Control and Feedback Systems",
        "principle_name_en": "PID Control and Feedback Systems",
        "ai_connection": "피드백 기반 학습 시스템, 학습률 조절, 모멘텀의 제어이론적 기원",
        "ai_connection_en": "Control-theoretic origin of feedback-based learning, learning rate adjustment, and momentum",
        "problem_solved": "오차를 실시간으로 감지하고 자동 보정하는 피드백 제어",
    },
    {
        "id": "ctrl_model_predictive_control",
        "discipline": "control_engineering",
        "discipline_name": "제어공학",
        "super_category": "공학",
        "principle_name": "Model Predictive Control (MPC)",
        "principle_name_en": "Model Predictive Control (MPC)",
        "ai_connection": "계획 기반 강화학습(MuZero, Dreamer)의 직접적 원류",
        "ai_connection_en": "Direct origin of planning-based reinforcement learning (MuZero, Dreamer)",
        "problem_solved": "미래를 예측하고 최적 행동 시퀀스를 실시간 계획",
    },
    # =========================================================================
    # 공학 > 전기/전자공학 (electrical_engineering)  [3 seeds]
    # =========================================================================
    {
        "id": "ee_fourier_transform",
        "discipline": "electrical_engineering",
        "discipline_name": "전기/전자공학",
        "super_category": "공학",
        "principle_name": "Fourier Transform and Spectral Analysis",
        "principle_name_en": "Fourier Transform and Spectral Analysis",
        "ai_connection": "CNN의 주파수 도메인 해석, FFT 기반 효율적 합성곱, 위치 인코딩",
        "ai_connection_en": "Frequency domain analysis of CNNs, FFT-based efficient convolution, positional encoding",
        "problem_solved": "신호를 주파수 성분으로 분해하여 분석하는 수학적 도구",
    },
    {
        "id": "ee_nyquist_sampling",
        "discipline": "electrical_engineering",
        "discipline_name": "전기/전자공학",
        "super_category": "공학",
        "principle_name": "Nyquist-Shannon Sampling Theorem",
        "principle_name_en": "Nyquist-Shannon Sampling Theorem",
        "ai_connection": "데이터 이산화의 이론적 기초, 앨리어싱과 다운샘플링",
        "ai_connection_en": "Theoretical basis for data discretization, aliasing and downsampling in neural networks",
        "problem_solved": "연속 신호를 정보 손실 없이 이산 데이터로 변환하는 조건",
    },
    {
        "id": "ee_quantization",
        "discipline": "electrical_engineering",
        "discipline_name": "전기/전자공학",
        "super_category": "공학",
        "principle_name": "Signal Quantization",
        "principle_name_en": "Signal Quantization",
        "ai_connection": "모델 양자화(INT8/INT4), 이진 신경망, 양자화 인식 학습의 직접적 이론 기반",
        "ai_connection_en": "Direct theoretical basis for model quantization (INT8/INT4), binary neural networks, quantization-aware training",
        "problem_solved": "연속 값을 유한한 이산 레벨로 표현할 때의 최적 전략",
    },
    # =========================================================================
    # 공학 > 정보/통신공학 (information_theory)  [4 seeds]
    # =========================================================================
    {
        "id": "info_shannon_entropy",
        "discipline": "information_theory",
        "discipline_name": "정보/통신공학",
        "super_category": "공학",
        "principle_name": "Shannon Entropy and Information Theory",
        "principle_name_en": "Shannon Entropy and Information Theory",
        "ai_connection": "크로스 엔트로피 손실함수, 정보 이득, 의사결정 트리의 수학적 토대",
        "ai_connection_en": "Mathematical foundation of cross-entropy loss, information gain, and decision trees",
        "problem_solved": "정보의 양을 정량적으로 측정하는 수학적 프레임워크",
    },
    {
        "id": "info_kl_divergence",
        "discipline": "information_theory",
        "discipline_name": "정보/통신공학",
        "super_category": "공학",
        "principle_name": "Kullback-Leibler Divergence",
        "principle_name_en": "Kullback-Leibler Divergence",
        "ai_connection": "VAE의 ELBO, 정책 경사법의 제약, 지식 증류의 핵심 측도",
        "ai_connection_en": "Core measure in VAE's ELBO, policy gradient constraints, and knowledge distillation",
        "problem_solved": "두 확률 분포 사이의 차이를 측정하는 비대칭 거리",
    },
    {
        "id": "info_channel_capacity",
        "discipline": "information_theory",
        "discipline_name": "정보/통신공학",
        "super_category": "공학",
        "principle_name": "Channel Capacity and Noisy Channel Coding",
        "principle_name_en": "Channel Capacity and Noisy Channel Coding",
        "ai_connection": "정보 병목 이론, 오토인코더의 정보 압축, 노이즈 주입 정규화",
        "ai_connection_en": "Information bottleneck theory, autoencoder compression, noise injection regularization",
        "problem_solved": "잡음이 있는 채널에서 신뢰할 수 있는 통신의 이론적 한계",
    },
    {
        "id": "info_mutual_information",
        "discipline": "information_theory",
        "discipline_name": "정보/통신공학",
        "super_category": "공학",
        "principle_name": "Mutual Information",
        "principle_name_en": "Mutual Information",
        "ai_connection": "자기지도 학습(contrastive learning)의 목적 함수, 특징 선택",
        "ai_connection_en": "Objective function of self-supervised contrastive learning, feature selection",
        "problem_solved": "두 확률 변수 사이의 상호 의존성 측정",
    },
    # =========================================================================
    # 공학 > 최적화공학 (optimization)  [5 seeds]
    # =========================================================================
    {
        "id": "opt_simulated_annealing",
        "discipline": "optimization",
        "discipline_name": "최적화공학",
        "super_category": "공학",
        "principle_name": "Simulated Annealing",
        "principle_name_en": "Simulated Annealing",
        "ai_connection": "금속 냉각 과정에서 영감받은 확률적 전역 최적화",
        "ai_connection_en": "Probabilistic global optimization inspired by metallurgical annealing",
        "problem_solved": "지역 최적에 갇히지 않는 전역 최적화",
    },
    {
        "id": "opt_gradient_descent",
        "discipline": "optimization",
        "discipline_name": "최적화공학",
        "super_category": "공학",
        "principle_name": "Gradient Descent and Stochastic Gradient Descent",
        "principle_name_en": "Gradient Descent and Stochastic Gradient Descent",
        "ai_connection": "딥러닝 학습의 핵심 알고리즘",
        "ai_connection_en": "Core algorithm of deep learning training",
        "problem_solved": "미분 가능한 함수의 최솟값을 반복적으로 찾는 방법",
    },
    {
        "id": "opt_convex_optimization",
        "discipline": "optimization",
        "discipline_name": "최적화공학",
        "super_category": "공학",
        "principle_name": "Convex Optimization and Duality",
        "principle_name_en": "Convex Optimization and Duality",
        "ai_connection": "SVM의 수학적 토대, 라그랑주 쌍대성, 제약 조건 학습",
        "ai_connection_en": "Mathematical foundation of SVM, Lagrangian duality, constrained learning",
        "problem_solved": "전역 최적해가 보장되는 최적화 문제의 체계적 풀이",
    },
    {
        "id": "opt_bayesian_optimization",
        "discipline": "optimization",
        "discipline_name": "최적화공학",
        "super_category": "공학",
        "principle_name": "Bayesian Optimization",
        "principle_name_en": "Bayesian Optimization",
        "ai_connection": "하이퍼파라미터 튜닝, 신경 구조 탐색(NAS)의 핵심 기법",
        "ai_connection_en": "Core technique for hyperparameter tuning and neural architecture search (NAS)",
        "problem_solved": "평가 비용이 높은 블랙박스 함수의 효율적 최적화",
    },
    {
        "id": "opt_evolutionary_algorithm",
        "discipline": "optimization",
        "discipline_name": "최적화공학",
        "super_category": "공학",
        "principle_name": "Evolutionary Algorithms and Genetic Programming",
        "principle_name_en": "Evolutionary Algorithms and Genetic Programming",
        "ai_connection": "진화 전략(OpenAI ES), 신경진화(NEAT), AutoML의 탐색 기법",
        "ai_connection_en": "Evolution strategies (OpenAI ES), neuroevolution (NEAT), AutoML search methods",
        "problem_solved": "그래디언트 없이 복잡한 탐색 공간에서 해를 진화시키는 방법",
    },
    # =========================================================================
    # 공학 > 로보틱스 (robotics)  [1 seed]
    # =========================================================================
    {
        "id": "robo_imitation_learning",
        "discipline": "robotics",
        "discipline_name": "로보틱스",
        "super_category": "공학",
        "principle_name": "Imitation Learning and Learning from Demonstration",
        "principle_name_en": "Imitation Learning and Learning from Demonstration",
        "ai_connection": "Bandura 관찰학습 → 행동 복제(BC) → IRL → GAIL → RLHF의 인지과학-AI 계보",
        "ai_connection_en": "Cognitive science lineage from Bandura's observational learning → BC → IRL → GAIL → RLHF",
        "problem_solved": "인지심리학의 관찰학습 원리를 계산적으로 구현하여 시연으로부터 정책 학습",
    },
    # =========================================================================
    # 자연과학 > 물리학 (physics)  [4 seeds]
    # =========================================================================
    {
        "id": "phys_boltzmann_distribution",
        "discipline": "physics",
        "discipline_name": "물리학",
        "super_category": "자연과학",
        "principle_name": "Boltzmann Distribution and Statistical Mechanics",
        "principle_name_en": "Boltzmann Distribution and Statistical Mechanics",
        "ai_connection": "볼츠만 머신, 에너지 기반 모델, 소프트맥스 함수의 직접적 기원",
        "ai_connection_en": "Direct origin of Boltzmann machines, energy-based models, and softmax function",
        "problem_solved": "열평형 상태의 입자 에너지 분포를 확률적으로 기술",
    },
    {
        "id": "phys_diffusion_process",
        "discipline": "physics",
        "discipline_name": "물리학",
        "super_category": "자연과학",
        "principle_name": "Diffusion Process and Stochastic Differential Equations",
        "principle_name_en": "Diffusion Process and Stochastic Differential Equations",
        "ai_connection": "확산 모델(DDPM, Stable Diffusion)의 직접적 물리학적 기원",
        "ai_connection_en": "Direct physical origin of diffusion models (DDPM, Stable Diffusion)",
        "problem_solved": "입자의 무작위 확산 운동을 수학적으로 기술",
    },
    {
        "id": "phys_hopfield_network",
        "discipline": "physics",
        "discipline_name": "물리학",
        "super_category": "자연과학",
        "principle_name": "Hopfield Network and Spin Glass Models",
        "principle_name_en": "Hopfield Network and Spin Glass Models",
        "ai_connection": "연상 기억 네트워크, 에너지 기반 학습, 현대 Transformer와의 재해석",
        "ai_connection_en": "Associative memory networks, energy-based learning, modern reinterpretation with Transformers",
        "problem_solved": "스핀 유리 모델로 연상 기억과 패턴 복원을 구현",
    },
    {
        "id": "phys_renormalization_group",
        "discipline": "physics",
        "discipline_name": "물리학",
        "super_category": "자연과학",
        "principle_name": "Renormalization Group",
        "principle_name_en": "Renormalization Group",
        "ai_connection": "심층 신경망의 다중 스케일 특징 추출과의 구조적 유사성",
        "ai_connection_en": "Structural analogy with multi-scale feature extraction in deep neural networks",
        "problem_solved": "물리 시스템의 다중 스케일 구조를 체계적으로 분석",
    },
    # =========================================================================
    # 자연과학 > 생물학 (biology)  [3 seeds]
    # =========================================================================
    {
        "id": "bio_natural_selection",
        "discipline": "biology",
        "discipline_name": "생물학",
        "super_category": "자연과학",
        "principle_name": "Natural Selection and Evolutionary Computation",
        "principle_name_en": "Natural Selection and Evolutionary Computation",
        "ai_connection": "유전 알고리즘, 진화 전략, 신경진화(NEAT)의 직접적 영감",
        "ai_connection_en": "Direct inspiration for genetic algorithms, evolution strategies, and neuroevolution (NEAT)",
        "problem_solved": "자연선택의 메커니즘이 계산적 최적화에 영감을 제공",
    },
    {
        "id": "bio_hebbian_learning",
        "discipline": "biology",
        "discipline_name": "생물학",
        "super_category": "자연과학",
        "principle_name": "Hebbian Learning and Synaptic Plasticity",
        "principle_name_en": "Hebbian Learning and Synaptic Plasticity",
        "ai_connection": "연결주의 학습 규칙, 비지도 학습, 자기 조직화의 생물학적 기원",
        "ai_connection_en": "Biological origin of connectionist learning rules, unsupervised learning, and self-organization",
        "problem_solved": "시냅스 수준의 학습 메커니즘에서 계산적 학습 규칙 도출",
    },
    {
        "id": "bio_swarm_intelligence",
        "discipline": "biology",
        "discipline_name": "생물학",
        "super_category": "자연과학",
        "principle_name": "Swarm Intelligence",
        "principle_name_en": "Swarm Intelligence",
        "ai_connection": "입자 군집 최적화(PSO), 개미 군집 최적화(ACO), 분산 AI 시스템",
        "ai_connection_en": "Particle swarm optimization (PSO), ant colony optimization (ACO), distributed AI systems",
        "problem_solved": "단순한 개체들의 집단 행동에서 복잡한 문제 해결 능력 출현",
    },
    # =========================================================================
    # 자연과학 > 화학 (chemistry)  [1 seed]
    # =========================================================================
    {
        "id": "chem_molecular_graph",
        "discipline": "chemistry",
        "discipline_name": "화학",
        "super_category": "자연과학",
        "principle_name": "Molecular Graph Representation",
        "principle_name_en": "Molecular Graph Representation",
        "ai_connection": "그래프 신경망(GNN)의 핵심 응용, 분자 속성 예측",
        "ai_connection_en": "Core application of graph neural networks (GNN), molecular property prediction",
        "problem_solved": "분자 구조를 그래프로 표현하여 화학적 성질을 예측",
    },
    # =========================================================================
    # 자연과학 > 신경과학 (neuroscience)  [4 seeds]
    # =========================================================================
    {
        "id": "neuro_visual_cortex_cnn",
        "discipline": "neuroscience",
        "discipline_name": "신경과학",
        "super_category": "자연과학",
        "principle_name": "Visual Cortex Hierarchy and Convolutional Neural Networks",
        "principle_name_en": "Visual Cortex Hierarchy and Convolutional Neural Networks",
        "ai_connection": "CNN의 직접적 생물학적 영감 — AI 역사상 가장 성공적인 학제간 영감",
        "ai_connection_en": "Direct biological inspiration for CNNs — the most successful interdisciplinary inspiration in AI history",
        "problem_solved": "시각 피질의 계층적 특징 추출 구조에서 CNN 아키텍처 도출",
    },
    {
        "id": "neuro_dopamine_td",
        "discipline": "neuroscience",
        "discipline_name": "신경과학",
        "super_category": "자연과학",
        "principle_name": "Dopamine Reward Prediction Error",
        "principle_name_en": "Dopamine Reward Prediction Error",
        "ai_connection": "시간차 학습(TD learning)과 도파민 신호의 놀라운 수렴",
        "ai_connection_en": "Remarkable convergence between TD learning and dopamine signaling",
        "problem_solved": "보상 예측 오차 신호가 학습을 이끄는 메커니즘",
    },
    {
        "id": "neuro_attention_mechanism",
        "discipline": "neuroscience",
        "discipline_name": "신경과학",
        "super_category": "자연과학",
        "principle_name": "Selective Attention in the Brain",
        "principle_name_en": "Selective Attention in the Brain",
        "ai_connection": "인지심리학의 선택적 주의 개념이 이름과 직관을 제공했으나 수학적 구현은 독립적으로 발전",
        "ai_connection_en": "Cognitive psychology's selective attention concept provided name and intuition, but mathematical implementation evolved independently",
        "problem_solved": "방대한 감각 입력 중 관련 정보를 선택적으로 처리",
    },
    {
        "id": "neuro_synaptic_plasticity_backprop",
        "discipline": "neuroscience",
        "discipline_name": "신경과학",
        "super_category": "자연과학",
        "principle_name": "Synaptic Plasticity and the Backpropagation Debate",
        "principle_name_en": "Synaptic Plasticity and the Backpropagation Debate",
        "ai_connection": "신경과학의 비판이 피드백 정렬, 예측 부호화, Forward-Forward 등 새로운 AI 학습 알고리즘을 촉발",
        "ai_connection_en": "Neuroscience critique driving new AI learning algorithms: feedback alignment, predictive coding, Forward-Forward",
        "problem_solved": "역전파의 생물학적 불가능성이 만든 긴장이 대안적 학습 규칙 연구를 추동",
    },
    # =========================================================================
    # 형식과학 > 수학 (mathematics)  [4 seeds]
    # =========================================================================
    {
        "id": "math_linear_algebra_nn",
        "discipline": "mathematics",
        "discipline_name": "수학",
        "super_category": "형식과학",
        "principle_name": "Linear Algebra and Matrix Computation in Neural Networks",
        "principle_name_en": "Linear Algebra and Matrix Computation in Neural Networks",
        "ai_connection": "신경망의 모든 연산이 행렬 곱으로 표현되는 수학적 토대",
        "ai_connection_en": "Mathematical foundation where all neural network operations are expressed as matrix multiplications",
        "problem_solved": "신경망 연산을 행렬 연산으로 체계화하여 효율적 계산 가능",
    },
    {
        "id": "math_universal_approximation",
        "discipline": "mathematics",
        "discipline_name": "수학",
        "super_category": "형식과학",
        "principle_name": "Universal Approximation Theorem",
        "principle_name_en": "Universal Approximation Theorem",
        "ai_connection": "신경망이 임의의 함수를 근사할 수 있다는 이론적 보장",
        "ai_connection_en": "Theoretical guarantee that neural networks can approximate arbitrary functions",
        "problem_solved": "신경망의 표현력에 대한 근본적 이론적 보장",
    },
    {
        "id": "math_information_geometry",
        "discipline": "mathematics",
        "discipline_name": "수학",
        "super_category": "형식과학",
        "principle_name": "Information Geometry and Natural Gradient",
        "principle_name_en": "Information Geometry and Natural Gradient",
        "ai_connection": "Fisher 정보 행렬 기반 자연 경사법의 수학적 토대",
        "ai_connection_en": "Mathematical foundation of natural gradient descent based on the Fisher information matrix",
        "problem_solved": "확률 분포 공간의 기하학적 구조를 활용한 최적화",
    },
    {
        "id": "math_graph_theory_gnn",
        "discipline": "mathematics",
        "discipline_name": "수학",
        "super_category": "형식과학",
        "principle_name": "Graph Theory and Graph Neural Networks",
        "principle_name_en": "Graph Theory and Graph Neural Networks",
        "ai_connection": "GNN, 지식 그래프, 소셜 네트워크 분석의 수학적 기반",
        "ai_connection_en": "Mathematical foundation of GNNs, knowledge graphs, and social network analysis",
        "problem_solved": "비정형 관계 데이터를 그래프로 모델링하고 학습",
    },
    # =========================================================================
    # 형식과학 > 통계학 (statistics)  [4 seeds]
    # =========================================================================
    {
        "id": "stat_bayesian_inference",
        "discipline": "statistics",
        "discipline_name": "통계학",
        "super_category": "형식과학",
        "principle_name": "Bayesian Inference",
        "principle_name_en": "Bayesian Inference",
        "ai_connection": "사전/사후 분포, 베이지안 신경망, 불확실성 정량화의 수학적 토대",
        "ai_connection_en": "Mathematical foundation of prior/posterior distributions, Bayesian neural networks, and uncertainty quantification",
        "problem_solved": "데이터 관측을 통해 믿음을 체계적으로 갱신하는 방법",
    },
    {
        "id": "stat_maximum_likelihood",
        "discipline": "statistics",
        "discipline_name": "통계학",
        "super_category": "형식과학",
        "principle_name": "Maximum Likelihood Estimation",
        "principle_name_en": "Maximum Likelihood Estimation",
        "ai_connection": "크로스 엔트로피 손실, 로지스틱 회귀, 생성 모델 학습의 통계학적 기원",
        "ai_connection_en": "Statistical origin of cross-entropy loss, logistic regression, and generative model training",
        "problem_solved": "관측 데이터를 가장 잘 설명하는 파라미터 추정",
    },
    {
        "id": "stat_bias_variance_tradeoff",
        "discipline": "statistics",
        "discipline_name": "통계학",
        "super_category": "형식과학",
        "principle_name": "Bias-Variance Tradeoff",
        "principle_name_en": "Bias-Variance Tradeoff",
        "ai_connection": "과적합/과소적합, 모델 복잡도 선택, 정규화의 이론적 토대",
        "ai_connection_en": "Theoretical foundation of overfitting/underfitting, model complexity selection, and regularization",
        "problem_solved": "모델 복잡도와 일반화 성능 사이의 근본적 균형",
    },
    {
        "id": "stat_markov_chain_monte_carlo",
        "discipline": "statistics",
        "discipline_name": "통계학",
        "super_category": "형식과학",
        "principle_name": "Markov Chain Monte Carlo (MCMC)",
        "principle_name_en": "Markov Chain Monte Carlo (MCMC)",
        "ai_connection": "베이지안 추론의 실용적 도구, 에너지 기반 모델 학습, MCMC 기반 생성",
        "ai_connection_en": "Practical tool for Bayesian inference, energy-based model training, and MCMC-based generation",
        "problem_solved": "복잡한 확률 분포에서의 효율적 샘플링",
    },
    # =========================================================================
    # 응용과학 > 의학/생명과학 (medicine)  [2 seeds]
    # =========================================================================
    {
        "id": "med_clinical_trial_design",
        "discipline": "medicine",
        "discipline_name": "의학/생명과학",
        "super_category": "응용과학",
        "principle_name": "Randomized Controlled Trial and A/B Testing",
        "principle_name_en": "Randomized Controlled Trial and A/B Testing",
        "ai_connection": "A/B 테스팅, 다중 무장 밴딧(MAB), 적응적 실험 설계의 의학적 기원",
        "ai_connection_en": "Medical origin of A/B testing, multi-armed bandits (MAB), and adaptive experimental design",
        "problem_solved": "인과관계를 검증하기 위한 실험 설계의 황금 표준",
    },
    {
        "id": "med_epidemiology_network",
        "discipline": "medicine",
        "discipline_name": "의학/생명과학",
        "super_category": "응용과학",
        "principle_name": "Epidemiological Modeling and Network Diffusion",
        "principle_name_en": "Epidemiological Modeling and Network Diffusion",
        "ai_connection": "정보 전파 모델, 바이럴 마케팅 알고리즘, GNN 기반 전파 예측",
        "ai_connection_en": "Information diffusion models, viral marketing algorithms, GNN-based propagation prediction",
        "problem_solved": "전염병 확산의 수학적 모델링과 네트워크 상 전파 분석",
    },
]
