"""학제간 AI 인사이트 시드 데이터 -- 검증된 원리-AI 매핑"""

PRINCIPLE_SEEDS = [
    # =========================================================================
    # 공학 > 제어공학 (control_engineering)
    # =========================================================================
    {
        "id": "ctrl_pid_feedback",
        "discipline": "control_engineering",
        "discipline_name": "제어공학",
        "super_category": "공학",
        "principle_name": "PID 제어",
        "principle_name_en": "PID Control",
        "ai_connection": "피드백 루프 기반 학습률 조절",
        "ai_connection_en": "Feedback Loop Learning Rate Scheduling",
        "problem_solved": "학습 과정에서 발산 또는 정체를 방지하는 자동 조절",
    },
    {
        "id": "ctrl_stability",
        "discipline": "control_engineering",
        "discipline_name": "제어공학",
        "super_category": "공학",
        "principle_name": "리아푸노프 안정성",
        "principle_name_en": "Lyapunov Stability",
        "ai_connection": "모델 학습 수렴 보장",
        "ai_connection_en": "Training Convergence Guarantees",
        "problem_solved": "신경망 학습의 수렴성 분석 및 안정적 학습 보장",
    },
    {
        "id": "ctrl_state_space",
        "discipline": "control_engineering",
        "discipline_name": "제어공학",
        "super_category": "공학",
        "principle_name": "상태 공간 모델",
        "principle_name_en": "State-Space Model",
        "ai_connection": "은닉 상태 표현 (RNN/SSM)",
        "ai_connection_en": "Hidden State Representation in RNN/SSM",
        "problem_solved": "시퀀스 데이터에서 시간적 의존성 포착",
    },
    {
        "id": "ctrl_adaptive",
        "discipline": "control_engineering",
        "discipline_name": "제어공학",
        "super_category": "공학",
        "principle_name": "적응 제어",
        "principle_name_en": "Adaptive Control",
        "ai_connection": "적응형 학습률 (Adam, AdaGrad)",
        "ai_connection_en": "Adaptive Learning Rate Optimizers",
        "problem_solved": "변화하는 데이터 분포에 대한 자동 파라미터 조절",
    },
    {
        "id": "ctrl_observer",
        "discipline": "control_engineering",
        "discipline_name": "제어공학",
        "super_category": "공학",
        "principle_name": "칼만 필터 / 관측기",
        "principle_name_en": "Kalman Filter / Observer",
        "ai_connection": "은닉 상태 추정",
        "ai_connection_en": "Hidden State Estimation",
        "problem_solved": "부분 관측 환경에서 시스템 상태 추정",
    },
    {
        "id": "ctrl_robust",
        "discipline": "control_engineering",
        "discipline_name": "제어공학",
        "super_category": "공학",
        "principle_name": "강건 제어 (H-infinity)",
        "principle_name_en": "Robust Control (H-infinity)",
        "ai_connection": "적대적 학습 / 강건 최적화",
        "ai_connection_en": "Adversarial Training / Robust Optimization",
        "problem_solved": "입력 교란에도 성능을 유지하는 강건한 모델",
    },
    {
        "id": "ctrl_mpc",
        "discipline": "control_engineering",
        "discipline_name": "제어공학",
        "super_category": "공학",
        "principle_name": "모델 예측 제어 (MPC)",
        "principle_name_en": "Model Predictive Control",
        "ai_connection": "계획 기반 강화학습 (MuZero)",
        "ai_connection_en": "Planning-based RL (MuZero)",
        "problem_solved": "미래 보상을 예측하여 최적 행동 시퀀스 결정",
    },
    {
        "id": "ctrl_transfer_function",
        "discipline": "control_engineering",
        "discipline_name": "제어공학",
        "super_category": "공학",
        "principle_name": "전달 함수",
        "principle_name_en": "Transfer Function",
        "ai_connection": "활성화 함수 설계",
        "ai_connection_en": "Activation Function Design",
        "problem_solved": "입력-출력 비선형 변환을 통한 표현력 확보",
    },
    {
        "id": "ctrl_system_identification",
        "discipline": "control_engineering",
        "discipline_name": "제어공학",
        "super_category": "공학",
        "principle_name": "시스템 식별",
        "principle_name_en": "System Identification",
        "ai_connection": "세계 모델 학습 (World Model)",
        "ai_connection_en": "World Model Learning",
        "problem_solved": "환경 동역학을 데이터로부터 학습하여 시뮬레이션",
    },
    # =========================================================================
    # 공학 > 전기/전자공학 (electrical_engineering)
    # =========================================================================
    {
        "id": "ee_signal_processing",
        "discipline": "electrical_engineering",
        "discipline_name": "전기/전자공학",
        "super_category": "공학",
        "principle_name": "컨볼루션 (신호처리)",
        "principle_name_en": "Convolution (Signal Processing)",
        "ai_connection": "합성곱 신경망 (CNN)",
        "ai_connection_en": "Convolutional Neural Networks",
        "problem_solved": "이미지/신호에서 지역적 패턴을 효율적으로 탐지",
    },
    {
        "id": "ee_circuit_accelerator",
        "discipline": "electrical_engineering",
        "discipline_name": "전기/전자공학",
        "super_category": "공학",
        "principle_name": "집적 회로 설계",
        "principle_name_en": "Integrated Circuit Design",
        "ai_connection": "AI 하드웨어 가속기 (GPU/TPU)",
        "ai_connection_en": "AI Hardware Accelerators (GPU/TPU)",
        "problem_solved": "대규모 행렬 연산의 병렬 처리로 학습 속도 향상",
    },
    {
        "id": "ee_filtering",
        "discipline": "electrical_engineering",
        "discipline_name": "전기/전자공학",
        "super_category": "공학",
        "principle_name": "디지털 필터링",
        "principle_name_en": "Digital Filtering",
        "ai_connection": "노이즈 제거 / 디노이징",
        "ai_connection_en": "Denoising (Diffusion Models)",
        "problem_solved": "데이터에서 노이즈를 분리하여 깨끗한 신호 복원",
    },
    {
        "id": "ee_fourier",
        "discipline": "electrical_engineering",
        "discipline_name": "전기/전자공학",
        "super_category": "공학",
        "principle_name": "푸리에 변환",
        "principle_name_en": "Fourier Transform",
        "ai_connection": "주파수 도메인 분석 / FFT 가속",
        "ai_connection_en": "Frequency Domain Analysis / FFT Acceleration",
        "problem_solved": "시계열 및 이미지의 주파수 성분 분리와 고속 연산",
    },
    {
        "id": "ee_adc_quantization",
        "discipline": "electrical_engineering",
        "discipline_name": "전기/전자공학",
        "super_category": "공학",
        "principle_name": "ADC 양자화",
        "principle_name_en": "ADC Quantization",
        "ai_connection": "모델 양자화 (INT8/INT4)",
        "ai_connection_en": "Model Quantization",
        "problem_solved": "모델 크기와 연산량 축소로 엣지 디바이스 배포 가능",
    },
    {
        "id": "ee_sampling_theorem",
        "discipline": "electrical_engineering",
        "discipline_name": "전기/전자공학",
        "super_category": "공학",
        "principle_name": "나이퀴스트 샘플링 정리",
        "principle_name_en": "Nyquist Sampling Theorem",
        "ai_connection": "데이터 샘플링 전략",
        "ai_connection_en": "Data Sampling Strategy",
        "problem_solved": "정보 손실 없이 최소한의 데이터로 신호 재구성",
    },
    {
        "id": "ee_modulation",
        "discipline": "electrical_engineering",
        "discipline_name": "전기/전자공학",
        "super_category": "공학",
        "principle_name": "변조 (Modulation)",
        "principle_name_en": "Modulation",
        "ai_connection": "임베딩 공간 매핑",
        "ai_connection_en": "Embedding Space Mapping",
        "problem_solved": "고차원 정보를 전송/처리에 적합한 표현으로 변환",
    },
    {
        "id": "ee_feedback_amplifier",
        "discipline": "electrical_engineering",
        "discipline_name": "전기/전자공학",
        "super_category": "공학",
        "principle_name": "피드백 증폭기",
        "principle_name_en": "Feedback Amplifier",
        "ai_connection": "잔차 연결 (Residual Connection)",
        "ai_connection_en": "Residual Connections (ResNet)",
        "problem_solved": "심층 신경망에서 기울기 소실 문제 해결",
    },
    # =========================================================================
    # 공학 > 정보/통신공학 (information_theory)
    # =========================================================================
    {
        "id": "info_shannon_entropy",
        "discipline": "information_theory",
        "discipline_name": "정보/통신공학",
        "super_category": "공학",
        "principle_name": "샤논 엔트로피",
        "principle_name_en": "Shannon Entropy",
        "ai_connection": "크로스 엔트로피 손실함수",
        "ai_connection_en": "Cross-Entropy Loss Function",
        "problem_solved": "분류 모델의 예측 확률 분포 최적화",
    },
    {
        "id": "info_channel_coding",
        "discipline": "information_theory",
        "discipline_name": "정보/통신공학",
        "super_category": "공학",
        "principle_name": "채널 코딩 (오류 정정)",
        "principle_name_en": "Channel Coding (Error Correction)",
        "ai_connection": "드롭아웃 / 정규화를 통한 오류 내성",
        "ai_connection_en": "Dropout / Regularization for Error Tolerance",
        "problem_solved": "노이즈가 있는 데이터에서도 올바른 예측 유지",
    },
    {
        "id": "info_compression",
        "discipline": "information_theory",
        "discipline_name": "정보/통신공학",
        "super_category": "공학",
        "principle_name": "데이터 압축 (허프만/LZ)",
        "principle_name_en": "Data Compression (Huffman/LZ)",
        "ai_connection": "토큰화 (BPE/WordPiece)",
        "ai_connection_en": "Tokenization (BPE/WordPiece)",
        "problem_solved": "자연어를 효율적인 이산 단위로 변환하여 처리",
    },
    {
        "id": "info_capacity",
        "discipline": "information_theory",
        "discipline_name": "정보/통신공학",
        "super_category": "공학",
        "principle_name": "채널 용량 (샤논 한계)",
        "principle_name_en": "Channel Capacity (Shannon Limit)",
        "ai_connection": "모델 용량 / 표현력 한계",
        "ai_connection_en": "Model Capacity / Expressiveness Bounds",
        "problem_solved": "주어진 파라미터 수로 학습 가능한 정보량 한계 분석",
    },
    {
        "id": "info_mutual_information",
        "discipline": "information_theory",
        "discipline_name": "정보/통신공학",
        "super_category": "공학",
        "principle_name": "상호 정보량",
        "principle_name_en": "Mutual Information",
        "ai_connection": "대조 학습 (InfoNCE)",
        "ai_connection_en": "Contrastive Learning (InfoNCE)",
        "problem_solved": "표현 간 공유 정보를 최대화하여 자기지도 학습",
    },
    {
        "id": "info_rate_distortion",
        "discipline": "information_theory",
        "discipline_name": "정보/통신공학",
        "super_category": "공학",
        "principle_name": "율-왜곡 이론",
        "principle_name_en": "Rate-Distortion Theory",
        "ai_connection": "변분 오토인코더 (VAE) 정보 병목",
        "ai_connection_en": "VAE Information Bottleneck",
        "problem_solved": "압축 수준과 복원 품질 간 최적 트레이드오프 결정",
    },
    {
        "id": "info_source_coding",
        "discipline": "information_theory",
        "discipline_name": "정보/통신공학",
        "super_category": "공학",
        "principle_name": "소스 코딩 (엔트로피 코딩)",
        "principle_name_en": "Source Coding (Entropy Coding)",
        "ai_connection": "잠재 표현 학습 (Latent Representation)",
        "ai_connection_en": "Latent Representation Learning",
        "problem_solved": "데이터의 핵심 정보를 저차원 공간에 효율적으로 인코딩",
    },
    {
        "id": "info_kl_divergence",
        "discipline": "information_theory",
        "discipline_name": "정보/통신공학",
        "super_category": "공학",
        "principle_name": "KL 발산",
        "principle_name_en": "Kullback-Leibler Divergence",
        "ai_connection": "지식 증류 / VAE 손실함수",
        "ai_connection_en": "Knowledge Distillation / VAE Loss",
        "problem_solved": "두 확률 분포 간 차이를 측정하여 모델 학습 최적화",
    },
    # =========================================================================
    # 공학 > 최적화공학 (optimization)
    # =========================================================================
    {
        "id": "opt_lagrange",
        "discipline": "optimization",
        "discipline_name": "최적화공학",
        "super_category": "공학",
        "principle_name": "라그랑주 승수법",
        "principle_name_en": "Lagrange Multipliers",
        "ai_connection": "제약 조건부 최적화 (SVM)",
        "ai_connection_en": "Constrained Optimization (SVM)",
        "problem_solved": "제약 조건 하에서 최적 분류 경계 탐색",
    },
    {
        "id": "opt_convex",
        "discipline": "optimization",
        "discipline_name": "최적화공학",
        "super_category": "공학",
        "principle_name": "볼록 최적화",
        "principle_name_en": "Convex Optimization",
        "ai_connection": "손실 함수 설계",
        "ai_connection_en": "Loss Function Design",
        "problem_solved": "전역 최적해가 보장되는 학습 목표 설계",
    },
    {
        "id": "opt_gradient_descent",
        "discipline": "optimization",
        "discipline_name": "최적화공학",
        "super_category": "공학",
        "principle_name": "경사 하강법",
        "principle_name_en": "Gradient Descent",
        "ai_connection": "신경망 학습 (SGD/Adam)",
        "ai_connection_en": "Neural Network Training (SGD/Adam)",
        "problem_solved": "고차원 파라미터 공간에서 손실을 최소화하는 경로 탐색",
    },
    {
        "id": "opt_linear_programming",
        "discipline": "optimization",
        "discipline_name": "최적화공학",
        "super_category": "공학",
        "principle_name": "선형 계획법",
        "principle_name_en": "Linear Programming",
        "ai_connection": "자원 배분 / 스케줄링 AI",
        "ai_connection_en": "Resource Allocation / Scheduling AI",
        "problem_solved": "제한된 자원 하에서 최적의 배분 결정",
    },
    {
        "id": "opt_genetic_programming",
        "discipline": "optimization",
        "discipline_name": "최적화공학",
        "super_category": "공학",
        "principle_name": "유전적 프로그래밍",
        "principle_name_en": "Genetic Programming",
        "ai_connection": "AutoML / 신경 구조 탐색 (NAS)",
        "ai_connection_en": "AutoML / Neural Architecture Search",
        "problem_solved": "최적의 모델 구조를 자동으로 탐색",
    },
    {
        "id": "opt_simulated_annealing",
        "discipline": "optimization",
        "discipline_name": "최적화공학",
        "super_category": "공학",
        "principle_name": "담금질 기법",
        "principle_name_en": "Simulated Annealing",
        "ai_connection": "학습률 스케줄링 / 탐색-활용 균형",
        "ai_connection_en": "Learning Rate Scheduling / Exploration-Exploitation",
        "problem_solved": "지역 최적해 탈출을 위한 확률적 탐색 전략",
    },
    {
        "id": "opt_pareto",
        "discipline": "optimization",
        "discipline_name": "최적화공학",
        "super_category": "공학",
        "principle_name": "파레토 최적",
        "principle_name_en": "Pareto Optimality",
        "ai_connection": "다목적 최적화 (정확도 vs 속도)",
        "ai_connection_en": "Multi-Objective Optimization (Accuracy vs Speed)",
        "problem_solved": "상충하는 목표 간 최적의 트레이드오프 집합 탐색",
    },
    {
        "id": "opt_stochastic",
        "discipline": "optimization",
        "discipline_name": "최적화공학",
        "super_category": "공학",
        "principle_name": "확률적 최적화",
        "principle_name_en": "Stochastic Optimization",
        "ai_connection": "미니배치 SGD",
        "ai_connection_en": "Mini-batch SGD",
        "problem_solved": "대규모 데이터에서 효율적인 기울기 추정 및 학습",
    },
    {
        "id": "opt_newton_method",
        "discipline": "optimization",
        "discipline_name": "최적화공학",
        "super_category": "공학",
        "principle_name": "뉴턴법 / 2차 최적화",
        "principle_name_en": "Newton's Method / Second-Order Optimization",
        "ai_connection": "자연 경사법 (Natural Gradient)",
        "ai_connection_en": "Natural Gradient Descent",
        "problem_solved": "곡률 정보를 활용한 빠른 수렴 학습",
    },
    # =========================================================================
    # 공학 > 로보틱스 (robotics)
    # =========================================================================
    {
        "id": "robo_path_planning",
        "discipline": "robotics",
        "discipline_name": "로보틱스",
        "super_category": "공학",
        "principle_name": "경로 계획 (A*/RRT)",
        "principle_name_en": "Path Planning (A*/RRT)",
        "ai_connection": "강화학습 기반 내비게이션",
        "ai_connection_en": "RL-based Navigation",
        "problem_solved": "동적 환경에서 최적 이동 경로 실시간 결정",
    },
    {
        "id": "robo_sensor_fusion",
        "discipline": "robotics",
        "discipline_name": "로보틱스",
        "super_category": "공학",
        "principle_name": "센서 퓨전",
        "principle_name_en": "Sensor Fusion",
        "ai_connection": "멀티모달 AI",
        "ai_connection_en": "Multimodal AI",
        "problem_solved": "이종 데이터(이미지+텍스트+센서)를 통합하여 판단",
    },
    {
        "id": "robo_slam",
        "discipline": "robotics",
        "discipline_name": "로보틱스",
        "super_category": "공학",
        "principle_name": "SLAM (동시 위치추정 및 지도작성)",
        "principle_name_en": "SLAM",
        "ai_connection": "자율주행 AI / 3D 씬 이해",
        "ai_connection_en": "Autonomous Driving / 3D Scene Understanding",
        "problem_solved": "미지 환경의 실시간 지도 생성과 자기 위치 추정",
    },
    {
        "id": "robo_inverse_kinematics",
        "discipline": "robotics",
        "discipline_name": "로보틱스",
        "super_category": "공학",
        "principle_name": "역기구학",
        "principle_name_en": "Inverse Kinematics",
        "ai_connection": "로봇 팔 제어 학습",
        "ai_connection_en": "Robotic Arm Control Learning",
        "problem_solved": "목표 위치에 도달하기 위한 관절 각도 자동 계산",
    },
    {
        "id": "robo_impedance",
        "discipline": "robotics",
        "discipline_name": "로보틱스",
        "super_category": "공학",
        "principle_name": "임피던스 제어",
        "principle_name_en": "Impedance Control",
        "ai_connection": "인간-로봇 상호작용 (HRI)",
        "ai_connection_en": "Human-Robot Interaction (HRI)",
        "problem_solved": "인간과 안전하게 협업하는 유연한 로봇 제어",
    },
    {
        "id": "robo_sim_to_real",
        "discipline": "robotics",
        "discipline_name": "로보틱스",
        "super_category": "공학",
        "principle_name": "시뮬레이션-실제 전이",
        "principle_name_en": "Sim-to-Real Transfer",
        "ai_connection": "도메인 적응 / 도메인 랜덤화",
        "ai_connection_en": "Domain Adaptation / Domain Randomization",
        "problem_solved": "시뮬레이션에서 학습한 정책을 실제 환경에 적용",
    },
    {
        "id": "robo_reward_shaping",
        "discipline": "robotics",
        "discipline_name": "로보틱스",
        "super_category": "공학",
        "principle_name": "보상 설계",
        "principle_name_en": "Reward Shaping",
        "ai_connection": "강화학습 보상 함수 설계",
        "ai_connection_en": "RL Reward Function Engineering",
        "problem_solved": "로봇이 원하는 행동을 학습하도록 보상 신호 설계",
    },
    {
        "id": "robo_swarm",
        "discipline": "robotics",
        "discipline_name": "로보틱스",
        "super_category": "공학",
        "principle_name": "군집 로봇",
        "principle_name_en": "Swarm Robotics",
        "ai_connection": "멀티에이전트 강화학습 (MARL)",
        "ai_connection_en": "Multi-Agent Reinforcement Learning",
        "problem_solved": "다수 에이전트의 분산 협업 전략 학습",
    },
    # =========================================================================
    # 자연과학 > 물리학 (physics)
    # =========================================================================
    {
        "id": "phys_thermodynamics",
        "discipline": "physics",
        "discipline_name": "물리학",
        "super_category": "자연과학",
        "principle_name": "열역학 (담금질)",
        "principle_name_en": "Thermodynamics (Annealing)",
        "ai_connection": "시뮬레이티드 어닐링",
        "ai_connection_en": "Simulated Annealing",
        "problem_solved": "조합 최적화 문제에서 전역 최적해 탐색",
    },
    {
        "id": "phys_quantum",
        "discipline": "physics",
        "discipline_name": "물리학",
        "super_category": "자연과학",
        "principle_name": "양자역학 (중첩/얽힘)",
        "principle_name_en": "Quantum Mechanics (Superposition/Entanglement)",
        "ai_connection": "양자 머신러닝 (QML)",
        "ai_connection_en": "Quantum Machine Learning",
        "problem_solved": "양자 병렬성을 활용한 지수적 탐색 공간 처리",
    },
    {
        "id": "phys_stat_mech",
        "discipline": "physics",
        "discipline_name": "물리학",
        "super_category": "자연과학",
        "principle_name": "통계역학 (볼츠만 분포)",
        "principle_name_en": "Statistical Mechanics (Boltzmann Distribution)",
        "ai_connection": "볼츠만 머신 / 소프트맥스",
        "ai_connection_en": "Boltzmann Machines / Softmax",
        "problem_solved": "에너지 기반 확률 분포를 통한 생성 모델링",
    },
    {
        "id": "phys_wave_equation",
        "discipline": "physics",
        "discipline_name": "물리학",
        "super_category": "자연과학",
        "principle_name": "미분방정식 (파동/확산)",
        "principle_name_en": "Differential Equations (Wave/Diffusion)",
        "ai_connection": "신경 ODE / 확산 모델",
        "ai_connection_en": "Neural ODE / Diffusion Models",
        "problem_solved": "연속 시간 동역학을 신경망으로 모델링",
    },
    {
        "id": "phys_symmetry",
        "discipline": "physics",
        "discipline_name": "물리학",
        "super_category": "자연과학",
        "principle_name": "대칭성 (뇌터 정리)",
        "principle_name_en": "Symmetry (Noether's Theorem)",
        "ai_connection": "등변 신경망 (Equivariant NN)",
        "ai_connection_en": "Equivariant Neural Networks",
        "problem_solved": "물리적 대칭을 보존하는 AI 모델 설계",
    },
    {
        "id": "phys_hamiltonian",
        "discipline": "physics",
        "discipline_name": "물리학",
        "super_category": "자연과학",
        "principle_name": "해밀턴 역학",
        "principle_name_en": "Hamiltonian Mechanics",
        "ai_connection": "해밀턴 신경망 (HNN)",
        "ai_connection_en": "Hamiltonian Neural Networks",
        "problem_solved": "에너지 보존 법칙을 만족하는 물리 시뮬레이션 학습",
    },
    {
        "id": "phys_renormalization",
        "discipline": "physics",
        "discipline_name": "물리학",
        "super_category": "자연과학",
        "principle_name": "재규격화 (Renormalization)",
        "principle_name_en": "Renormalization Group",
        "ai_connection": "심층 신경망의 계층적 특징 추출",
        "ai_connection_en": "Hierarchical Feature Extraction in Deep Networks",
        "problem_solved": "다양한 스케일의 정보를 계층적으로 요약",
    },
    {
        "id": "phys_ising_model",
        "discipline": "physics",
        "discipline_name": "물리학",
        "super_category": "자연과학",
        "principle_name": "이징 모델",
        "principle_name_en": "Ising Model",
        "ai_connection": "홉필드 네트워크 / 에너지 기반 모델",
        "ai_connection_en": "Hopfield Network / Energy-Based Models",
        "problem_solved": "연상 기억과 패턴 복원",
    },
    {
        "id": "phys_relativity_spacetime",
        "discipline": "physics",
        "discipline_name": "물리학",
        "super_category": "자연과학",
        "principle_name": "민코프스키 시공간",
        "principle_name_en": "Minkowski Spacetime",
        "ai_connection": "쌍곡 임베딩 (Hyperbolic Embedding)",
        "ai_connection_en": "Hyperbolic Embeddings",
        "problem_solved": "계층적 구조를 가진 데이터를 저차원 쌍곡 공간에 임베딩",
    },
    # =========================================================================
    # 자연과학 > 생물학 (biology)
    # =========================================================================
    {
        "id": "bio_natural_selection",
        "discipline": "biology",
        "discipline_name": "생물학",
        "super_category": "자연과학",
        "principle_name": "자연선택 / 진화",
        "principle_name_en": "Natural Selection / Evolution",
        "ai_connection": "유전 알고리즘 (GA)",
        "ai_connection_en": "Genetic Algorithms",
        "problem_solved": "복잡한 최적화 문제에서 해의 진화적 탐색",
    },
    {
        "id": "bio_neuron",
        "discipline": "biology",
        "discipline_name": "생물학",
        "super_category": "자연과학",
        "principle_name": "생물학적 뉴런",
        "principle_name_en": "Biological Neuron",
        "ai_connection": "인공 신경망 (퍼셉트론)",
        "ai_connection_en": "Artificial Neural Networks (Perceptron)",
        "problem_solved": "생물 뉴런의 신호 전달 메커니즘을 모방한 학습 모델",
    },
    {
        "id": "bio_immune",
        "discipline": "biology",
        "discipline_name": "생물학",
        "super_category": "자연과학",
        "principle_name": "면역 체계 (항원-항체)",
        "principle_name_en": "Immune System (Antigen-Antibody)",
        "ai_connection": "이상 탐지 (Anomaly Detection)",
        "ai_connection_en": "Anomaly Detection",
        "problem_solved": "알려지지 않은 위협/이상 패턴 자동 탐지",
    },
    {
        "id": "bio_swarm",
        "discipline": "biology",
        "discipline_name": "생물학",
        "super_category": "자연과학",
        "principle_name": "군집 지능 (개미/벌)",
        "principle_name_en": "Swarm Intelligence (Ant/Bee Colony)",
        "ai_connection": "스웜 최적화 (ACO/PSO)",
        "ai_connection_en": "Swarm Optimization (ACO/PSO)",
        "problem_solved": "분산된 단순 에이전트의 협업으로 복잡한 문제 해결",
    },
    {
        "id": "bio_dna",
        "discipline": "biology",
        "discipline_name": "생물학",
        "super_category": "자연과학",
        "principle_name": "DNA 복제/전사/번역",
        "principle_name_en": "DNA Replication/Transcription/Translation",
        "ai_connection": "유전적 프로그래밍 / 단백질 구조 예측",
        "ai_connection_en": "Genetic Programming / Protein Structure Prediction",
        "problem_solved": "생물학적 서열에서 구조와 기능 예측 (AlphaFold)",
    },
    {
        "id": "bio_ecology",
        "discipline": "biology",
        "discipline_name": "생물학",
        "super_category": "자연과학",
        "principle_name": "생태적 니치 (적소)",
        "principle_name_en": "Ecological Niche",
        "ai_connection": "앙상블 다양성 / Mixture of Experts",
        "ai_connection_en": "Ensemble Diversity / Mixture of Experts",
        "problem_solved": "다양한 전문 모델이 각자 역할을 나눠 전체 성능 향상",
    },
    {
        "id": "bio_homeostasis",
        "discipline": "biology",
        "discipline_name": "생물학",
        "super_category": "자연과학",
        "principle_name": "항상성 (Homeostasis)",
        "principle_name_en": "Homeostasis",
        "ai_connection": "배치 정규화 / 레이어 정규화",
        "ai_connection_en": "Batch Normalization / Layer Normalization",
        "problem_solved": "학습 중 내부 상태를 안정적으로 유지",
    },
    {
        "id": "bio_symbiosis",
        "discipline": "biology",
        "discipline_name": "생물학",
        "super_category": "자연과학",
        "principle_name": "공생 (Symbiosis)",
        "principle_name_en": "Symbiosis",
        "ai_connection": "협력적 멀티에이전트 시스템",
        "ai_connection_en": "Cooperative Multi-Agent Systems",
        "problem_solved": "에이전트 간 협력을 통한 상호 이익 극대화",
    },
    {
        "id": "bio_mutation",
        "discipline": "biology",
        "discipline_name": "생물학",
        "super_category": "자연과학",
        "principle_name": "돌연변이",
        "principle_name_en": "Mutation",
        "ai_connection": "탐색 노이즈 / 데이터 증강",
        "ai_connection_en": "Exploration Noise / Data Augmentation",
        "problem_solved": "지역 최적에서 탈출하고 학습 데이터 다양성 확보",
    },
    # =========================================================================
    # 자연과학 > 신경과학 (neuroscience)
    # =========================================================================
    {
        "id": "neuro_synaptic_plasticity",
        "discipline": "neuroscience",
        "discipline_name": "신경과학",
        "super_category": "자연과학",
        "principle_name": "시냅스 가소성 (헤브 학습)",
        "principle_name_en": "Synaptic Plasticity (Hebbian Learning)",
        "ai_connection": "가중치 갱신 / 학습률",
        "ai_connection_en": "Weight Update / Learning Rate",
        "problem_solved": "경험에 기반한 연결 강도 자동 조절",
    },
    {
        "id": "neuro_visual_cortex",
        "discipline": "neuroscience",
        "discipline_name": "신경과학",
        "super_category": "자연과학",
        "principle_name": "시각 피질 (V1 단순/복합 세포)",
        "principle_name_en": "Visual Cortex (V1 Simple/Complex Cells)",
        "ai_connection": "합성곱 신경망 (CNN) 구조",
        "ai_connection_en": "CNN Architecture",
        "problem_solved": "계층적 시각 특징 추출 (엣지 -> 텍스처 -> 객체)",
    },
    {
        "id": "neuro_hippocampus",
        "discipline": "neuroscience",
        "discipline_name": "신경과학",
        "super_category": "자연과학",
        "principle_name": "해마 (장기 기억 저장)",
        "principle_name_en": "Hippocampus (Long-term Memory)",
        "ai_connection": "메모리 네트워크 / 경험 리플레이",
        "ai_connection_en": "Memory Networks / Experience Replay",
        "problem_solved": "과거 경험을 저장하고 재활용하여 학습 효율 향상",
    },
    {
        "id": "neuro_dopamine",
        "discipline": "neuroscience",
        "discipline_name": "신경과학",
        "super_category": "자연과학",
        "principle_name": "도파민 보상 신호",
        "principle_name_en": "Dopamine Reward Signal",
        "ai_connection": "TD 오차 (시간차 학습)",
        "ai_connection_en": "Temporal Difference Error",
        "problem_solved": "예측과 실제 보상 간 차이를 학습 신호로 활용",
    },
    {
        "id": "neuro_attention",
        "discipline": "neuroscience",
        "discipline_name": "신경과학",
        "super_category": "자연과학",
        "principle_name": "선택적 주의 (Selective Attention)",
        "principle_name_en": "Selective Attention",
        "ai_connection": "Attention 메커니즘 / Transformer",
        "ai_connection_en": "Attention Mechanism / Transformer",
        "problem_solved": "입력의 중요한 부분에 선택적으로 집중하여 처리",
    },
    {
        "id": "neuro_sparse_coding",
        "discipline": "neuroscience",
        "discipline_name": "신경과학",
        "super_category": "자연과학",
        "principle_name": "희소 코딩 (Sparse Coding)",
        "principle_name_en": "Sparse Coding",
        "ai_connection": "희소 오토인코더 / L1 정규화",
        "ai_connection_en": "Sparse Autoencoder / L1 Regularization",
        "problem_solved": "소수의 활성 뉴런만으로 효율적인 표현 학습",
    },
    {
        "id": "neuro_working_memory",
        "discipline": "neuroscience",
        "discipline_name": "신경과학",
        "super_category": "자연과학",
        "principle_name": "작업 기억 (전전두엽)",
        "principle_name_en": "Working Memory (Prefrontal Cortex)",
        "ai_connection": "LSTM 게이트 / 컨텍스트 윈도우",
        "ai_connection_en": "LSTM Gates / Context Window",
        "problem_solved": "단기적으로 필요한 정보를 유지하고 불필요한 정보 삭제",
    },
    {
        "id": "neuro_sleep_consolidation",
        "discipline": "neuroscience",
        "discipline_name": "신경과학",
        "super_category": "자연과학",
        "principle_name": "수면 중 기억 통합",
        "principle_name_en": "Sleep Memory Consolidation",
        "ai_connection": "오프라인 학습 / 경험 리플레이",
        "ai_connection_en": "Offline Learning / Experience Replay",
        "problem_solved": "이전 경험을 반복 재생하여 지식 공고화",
    },
    {
        "id": "neuro_lateral_inhibition",
        "discipline": "neuroscience",
        "discipline_name": "신경과학",
        "super_category": "자연과학",
        "principle_name": "측면 억제 (Lateral Inhibition)",
        "principle_name_en": "Lateral Inhibition",
        "ai_connection": "소프트맥스 / Winner-Take-All",
        "ai_connection_en": "Softmax / Winner-Take-All",
        "problem_solved": "경쟁적 억제를 통해 가장 강한 신호만 선택",
    },
    # =========================================================================
    # 형식과학 > 수학 (mathematics)
    # =========================================================================
    {
        "id": "math_linear_algebra",
        "discipline": "mathematics",
        "discipline_name": "수학",
        "super_category": "형식과학",
        "principle_name": "선형대수 (행렬 연산)",
        "principle_name_en": "Linear Algebra (Matrix Operations)",
        "ai_connection": "텐서 연산 / GPU 병렬 계산",
        "ai_connection_en": "Tensor Operations / GPU Parallel Computation",
        "problem_solved": "신경망의 핵심 연산인 행렬 곱셈 효율적 수행",
    },
    {
        "id": "math_calculus",
        "discipline": "mathematics",
        "discipline_name": "수학",
        "super_category": "형식과학",
        "principle_name": "미적분 (연쇄 법칙)",
        "principle_name_en": "Calculus (Chain Rule)",
        "ai_connection": "역전파 알고리즘 (Backpropagation)",
        "ai_connection_en": "Backpropagation Algorithm",
        "problem_solved": "다층 신경망에서 각 가중치의 기울기 효율적 계산",
    },
    {
        "id": "math_probability",
        "discipline": "mathematics",
        "discipline_name": "수학",
        "super_category": "형식과학",
        "principle_name": "확률론",
        "principle_name_en": "Probability Theory",
        "ai_connection": "생성 모델 (VAE, GAN, Diffusion)",
        "ai_connection_en": "Generative Models (VAE, GAN, Diffusion)",
        "problem_solved": "데이터의 확률 분포를 학습하여 새로운 샘플 생성",
    },
    {
        "id": "math_graph_theory",
        "discipline": "mathematics",
        "discipline_name": "수학",
        "super_category": "형식과학",
        "principle_name": "그래프 이론",
        "principle_name_en": "Graph Theory",
        "ai_connection": "그래프 신경망 (GNN)",
        "ai_connection_en": "Graph Neural Networks (GNN)",
        "problem_solved": "소셜네트워크/분자구조 등 그래프 데이터 학습",
    },
    {
        "id": "math_topology",
        "discipline": "mathematics",
        "discipline_name": "수학",
        "super_category": "형식과학",
        "principle_name": "위상수학 (지속 호몰로지)",
        "principle_name_en": "Topology (Persistent Homology)",
        "ai_connection": "위상적 데이터 분석 (TDA)",
        "ai_connection_en": "Topological Data Analysis (TDA)",
        "problem_solved": "데이터의 형태학적 특성(구멍, 연결성) 파악",
    },
    {
        "id": "math_svd",
        "discipline": "mathematics",
        "discipline_name": "수학",
        "super_category": "형식과학",
        "principle_name": "특이값 분해 (SVD)",
        "principle_name_en": "Singular Value Decomposition (SVD)",
        "ai_connection": "차원 축소 / 추천 시스템",
        "ai_connection_en": "Dimensionality Reduction / Recommender Systems",
        "problem_solved": "고차원 행렬을 저랭크로 근사하여 핵심 패턴 추출",
    },
    {
        "id": "math_manifold",
        "discipline": "mathematics",
        "discipline_name": "수학",
        "super_category": "형식과학",
        "principle_name": "다양체 이론 (Manifold)",
        "principle_name_en": "Manifold Theory",
        "ai_connection": "매니폴드 학습 (t-SNE, UMAP)",
        "ai_connection_en": "Manifold Learning (t-SNE, UMAP)",
        "problem_solved": "고차원 데이터가 놓인 저차원 구조를 발견하여 시각화",
    },
    {
        "id": "math_measure_theory",
        "discipline": "mathematics",
        "discipline_name": "수학",
        "super_category": "형식과학",
        "principle_name": "측도론 / 적분론",
        "principle_name_en": "Measure Theory / Integration",
        "ai_connection": "확률적 프레임워크 / 기댓값 기반 학습",
        "ai_connection_en": "Probabilistic Frameworks / Expected Value Learning",
        "problem_solved": "손실 함수의 기댓값 최소화를 수학적으로 정당화",
    },
    {
        "id": "math_functional_analysis",
        "discipline": "mathematics",
        "discipline_name": "수학",
        "super_category": "형식과학",
        "principle_name": "함수 해석학 (커널)",
        "principle_name_en": "Functional Analysis (Kernel Methods)",
        "ai_connection": "커널 SVM / RKHS",
        "ai_connection_en": "Kernel SVM / RKHS",
        "problem_solved": "비선형 데이터를 고차원 공간에 매핑하여 선형 분리",
    },
    # =========================================================================
    # 형식과학 > 통계학 (statistics)
    # =========================================================================
    {
        "id": "stat_bayes",
        "discipline": "statistics",
        "discipline_name": "통계학",
        "super_category": "형식과학",
        "principle_name": "베이즈 정리",
        "principle_name_en": "Bayes' Theorem",
        "ai_connection": "베이지안 신경망 / 확률 모델",
        "ai_connection_en": "Bayesian Neural Networks / Probabilistic Models",
        "problem_solved": "사전 지식을 활용한 불확실성 정량화",
    },
    {
        "id": "stat_normal_distribution",
        "discipline": "statistics",
        "discipline_name": "통계학",
        "super_category": "형식과학",
        "principle_name": "정규분포 (중심극한정리)",
        "principle_name_en": "Normal Distribution (CLT)",
        "ai_connection": "배치 정규화 / 가중치 초기화",
        "ai_connection_en": "Batch Normalization / Weight Initialization",
        "problem_solved": "학습 안정성을 위한 데이터/가중치 분포 정규화",
    },
    {
        "id": "stat_mle",
        "discipline": "statistics",
        "discipline_name": "통계학",
        "super_category": "형식과학",
        "principle_name": "최대우도추정 (MLE)",
        "principle_name_en": "Maximum Likelihood Estimation",
        "ai_connection": "신경망 학습 목표 (손실 함수)",
        "ai_connection_en": "Training Objective (Loss Function)",
        "problem_solved": "관측 데이터의 우도를 최대화하는 모델 파라미터 추정",
    },
    {
        "id": "stat_bootstrap",
        "discipline": "statistics",
        "discipline_name": "통계학",
        "super_category": "형식과학",
        "principle_name": "부트스트래핑",
        "principle_name_en": "Bootstrapping",
        "ai_connection": "앙상블 학습 (배깅/랜덤포레스트)",
        "ai_connection_en": "Ensemble Learning (Bagging/Random Forest)",
        "problem_solved": "복원 추출 기반 다수 모델로 분산 감소",
    },
    {
        "id": "stat_hypothesis",
        "discipline": "statistics",
        "discipline_name": "통계학",
        "super_category": "형식과학",
        "principle_name": "가설 검정 (p-value)",
        "principle_name_en": "Hypothesis Testing (p-value)",
        "ai_connection": "A/B 테스트 / 모델 비교",
        "ai_connection_en": "A/B Testing / Model Comparison",
        "problem_solved": "모델 성능 차이가 통계적으로 유의한지 판단",
    },
    {
        "id": "stat_regression",
        "discipline": "statistics",
        "discipline_name": "통계학",
        "super_category": "형식과학",
        "principle_name": "회귀 분석",
        "principle_name_en": "Regression Analysis",
        "ai_connection": "선형/로지스틱 회귀 모델",
        "ai_connection_en": "Linear/Logistic Regression Models",
        "problem_solved": "변수 간 관계를 모델링하여 예측",
    },
    {
        "id": "stat_bias_variance",
        "discipline": "statistics",
        "discipline_name": "통계학",
        "super_category": "형식과학",
        "principle_name": "편향-분산 트레이드오프",
        "principle_name_en": "Bias-Variance Tradeoff",
        "ai_connection": "모델 복잡도 선택 / 정규화",
        "ai_connection_en": "Model Complexity Selection / Regularization",
        "problem_solved": "과적합과 과소적합 사이 최적 모델 복잡도 결정",
    },
    {
        "id": "stat_cross_validation",
        "discipline": "statistics",
        "discipline_name": "통계학",
        "super_category": "형식과학",
        "principle_name": "교차 검증 (Cross-Validation)",
        "principle_name_en": "Cross-Validation",
        "ai_connection": "모델 일반화 성능 평가",
        "ai_connection_en": "Model Generalization Evaluation",
        "problem_solved": "제한된 데이터에서 모델의 실제 성능을 신뢰성 있게 추정",
    },
    {
        "id": "stat_markov_chain",
        "discipline": "statistics",
        "discipline_name": "통계학",
        "super_category": "형식과학",
        "principle_name": "마르코프 연쇄",
        "principle_name_en": "Markov Chain",
        "ai_connection": "MCMC 추론 / 은닉 마르코프 모델",
        "ai_connection_en": "MCMC Inference / Hidden Markov Models",
        "problem_solved": "복잡한 확률 분포로부터 효율적 샘플링",
    },
    {
        "id": "stat_dimensionality_reduction",
        "discipline": "statistics",
        "discipline_name": "통계학",
        "super_category": "형식과학",
        "principle_name": "주성분 분석 (PCA)",
        "principle_name_en": "Principal Component Analysis (PCA)",
        "ai_connection": "차원 축소 / 특성 추출",
        "ai_connection_en": "Dimensionality Reduction / Feature Extraction",
        "problem_solved": "고차원 데이터에서 가장 중요한 방향 추출",
    },
    # =========================================================================
    # 사회과학 > 심리학/인지과학 (psychology)
    # =========================================================================
    {
        "id": "psych_cognitive_bias",
        "discipline": "psychology",
        "discipline_name": "심리학/인지과학",
        "super_category": "사회과학",
        "principle_name": "인지 편향 (확증 편향 등)",
        "principle_name_en": "Cognitive Bias (Confirmation Bias)",
        "ai_connection": "AI 편향 / 공정성 문제",
        "ai_connection_en": "AI Bias / Fairness Issues",
        "problem_solved": "학습 데이터 편향이 모델 출력에 미치는 영향 분석",
    },
    {
        "id": "psych_attention",
        "discipline": "psychology",
        "discipline_name": "심리학/인지과학",
        "super_category": "사회과학",
        "principle_name": "주의 (선택적/분할적)",
        "principle_name_en": "Attention (Selective/Divided)",
        "ai_connection": "Attention 메커니즘",
        "ai_connection_en": "Attention Mechanism",
        "problem_solved": "제한된 처리 자원을 중요한 정보에 집중 배분",
    },
    {
        "id": "psych_working_memory",
        "discipline": "psychology",
        "discipline_name": "심리학/인지과학",
        "super_category": "사회과학",
        "principle_name": "작업 기억 (밀러의 법칙)",
        "principle_name_en": "Working Memory (Miller's Law)",
        "ai_connection": "컨텍스트 윈도우 / 단기 메모리",
        "ai_connection_en": "Context Window / Short-term Memory",
        "problem_solved": "처리 가능한 정보량의 한계와 청킹 전략",
    },
    {
        "id": "psych_reinforcement",
        "discipline": "psychology",
        "discipline_name": "심리학/인지과학",
        "super_category": "사회과학",
        "principle_name": "조작적 조건형성 (스키너)",
        "principle_name_en": "Operant Conditioning (Skinner)",
        "ai_connection": "강화학습 (보상/처벌 신호)",
        "ai_connection_en": "Reinforcement Learning (Reward/Punishment)",
        "problem_solved": "시행착오를 통한 최적 행동 정책 학습",
    },
    {
        "id": "psych_gestalt",
        "discipline": "psychology",
        "discipline_name": "심리학/인지과학",
        "super_category": "사회과학",
        "principle_name": "게슈탈트 원리",
        "principle_name_en": "Gestalt Principles",
        "ai_connection": "패턴 인식 / 객체 탐지",
        "ai_connection_en": "Pattern Recognition / Object Detection",
        "problem_solved": "부분적 정보로부터 전체 패턴을 인식하는 능력",
    },
    {
        "id": "psych_transfer",
        "discipline": "psychology",
        "discipline_name": "심리학/인지과학",
        "super_category": "사회과학",
        "principle_name": "전이 학습 (학습의 전이)",
        "principle_name_en": "Transfer of Learning",
        "ai_connection": "전이 학습 (Transfer Learning)",
        "ai_connection_en": "Transfer Learning / Fine-tuning",
        "problem_solved": "한 영역에서 배운 지식을 새로운 영역에 적용",
    },
    {
        "id": "psych_priming",
        "discipline": "psychology",
        "discipline_name": "심리학/인지과학",
        "super_category": "사회과학",
        "principle_name": "프라이밍 효과",
        "principle_name_en": "Priming Effect",
        "ai_connection": "프롬프트 엔지니어링 / In-context Learning",
        "ai_connection_en": "Prompt Engineering / In-context Learning",
        "problem_solved": "선행 맥락이 후속 처리에 미치는 영향 활용",
    },
    {
        "id": "psych_dual_process",
        "discipline": "psychology",
        "discipline_name": "심리학/인지과학",
        "super_category": "사회과학",
        "principle_name": "이중 처리 이론 (시스템1/2)",
        "principle_name_en": "Dual Process Theory (System 1/2)",
        "ai_connection": "빠른 추론 vs 느린 추론 (Chain-of-Thought)",
        "ai_connection_en": "Fast Inference vs Slow Reasoning (CoT)",
        "problem_solved": "직관적 빠른 응답과 숙고적 깊은 추론의 구분",
    },
    # =========================================================================
    # 사회과학 > 경제학/게임이론 (economics)
    # =========================================================================
    {
        "id": "econ_nash",
        "discipline": "economics",
        "discipline_name": "경제학/게임이론",
        "super_category": "사회과학",
        "principle_name": "내쉬 균형",
        "principle_name_en": "Nash Equilibrium",
        "ai_connection": "멀티에이전트 AI / GAN 학습 균형",
        "ai_connection_en": "Multi-Agent AI / GAN Training Equilibrium",
        "problem_solved": "경쟁적 에이전트 간 안정적 전략 균형 도달",
    },
    {
        "id": "econ_auction",
        "discipline": "economics",
        "discipline_name": "경제학/게임이론",
        "super_category": "사회과학",
        "principle_name": "경매 이론 (비크리 경매)",
        "principle_name_en": "Auction Theory (Vickrey Auction)",
        "ai_connection": "메커니즘 설계 / 광고 경매 AI",
        "ai_connection_en": "Mechanism Design / Ad Auction AI",
        "problem_solved": "참가자가 진실된 가치를 표현하는 최적 경매 설계",
    },
    {
        "id": "econ_supply_demand",
        "discipline": "economics",
        "discipline_name": "경제학/게임이론",
        "super_category": "사회과학",
        "principle_name": "수요 공급 법칙",
        "principle_name_en": "Supply and Demand",
        "ai_connection": "동적 가격 결정 AI",
        "ai_connection_en": "Dynamic Pricing AI",
        "problem_solved": "실시간 수요에 따른 최적 가격 자동 결정",
    },
    {
        "id": "econ_marginal_utility",
        "discipline": "economics",
        "discipline_name": "경제학/게임이론",
        "super_category": "사회과학",
        "principle_name": "한계 효용 체감 법칙",
        "principle_name_en": "Diminishing Marginal Utility",
        "ai_connection": "보상 감소 / 학습률 감쇠",
        "ai_connection_en": "Reward Decay / Learning Rate Decay",
        "problem_solved": "추가 데이터/학습의 수확 체감 모델링",
    },
    {
        "id": "econ_information_asymmetry",
        "discipline": "economics",
        "discipline_name": "경제학/게임이론",
        "super_category": "사회과학",
        "principle_name": "정보 비대칭 (레몬 시장)",
        "principle_name_en": "Information Asymmetry (Market for Lemons)",
        "ai_connection": "적대적 학습 / GAN",
        "ai_connection_en": "Adversarial Learning / GANs",
        "problem_solved": "정보 격차를 활용한 생성자-판별자 경쟁 학습",
    },
    {
        "id": "econ_principal_agent",
        "discipline": "economics",
        "discipline_name": "경제학/게임이론",
        "super_category": "사회과학",
        "principle_name": "주인-대리인 문제",
        "principle_name_en": "Principal-Agent Problem",
        "ai_connection": "AI 정렬 문제 (Alignment)",
        "ai_connection_en": "AI Alignment Problem",
        "problem_solved": "AI 시스템이 인간의 의도에 맞게 행동하도록 보장",
    },
    {
        "id": "econ_externality",
        "discipline": "economics",
        "discipline_name": "경제학/게임이론",
        "super_category": "사회과학",
        "principle_name": "외부효과 (외부성)",
        "principle_name_en": "Externality",
        "ai_connection": "AI 사회적 영향 분석",
        "ai_connection_en": "AI Social Impact Analysis",
        "problem_solved": "AI 의사결정이 관련 없는 집단에 미치는 영향 고려",
    },
    {
        "id": "econ_game_minimax",
        "discipline": "economics",
        "discipline_name": "경제학/게임이론",
        "super_category": "사회과학",
        "principle_name": "미니맥스 정리",
        "principle_name_en": "Minimax Theorem",
        "ai_connection": "게임 AI (체스/바둑 탐색)",
        "ai_connection_en": "Game AI (Chess/Go Search)",
        "problem_solved": "상대방의 최선 수에 대응하는 최적 전략 탐색",
    },
    {
        "id": "econ_market_efficiency",
        "discipline": "economics",
        "discipline_name": "경제학/게임이론",
        "super_category": "사회과학",
        "principle_name": "시장 효율성 가설",
        "principle_name_en": "Efficient Market Hypothesis",
        "ai_connection": "금융 예측 AI의 한계 분석",
        "ai_connection_en": "Limitations of Financial Prediction AI",
        "problem_solved": "공개 정보가 이미 반영된 시장에서 초과 수익의 어려움",
    },
    # =========================================================================
    # 인문학 > 철학/논리학 (philosophy)
    # =========================================================================
    {
        "id": "phil_propositional_logic",
        "discipline": "philosophy",
        "discipline_name": "철학/논리학",
        "super_category": "인문학",
        "principle_name": "명제 논리 / 술어 논리",
        "principle_name_en": "Propositional / Predicate Logic",
        "ai_connection": "추론 엔진 / 규칙 기반 AI",
        "ai_connection_en": "Inference Engine / Rule-Based AI",
        "problem_solved": "논리적 추론의 형식화 및 자동화",
    },
    {
        "id": "phil_induction",
        "discipline": "philosophy",
        "discipline_name": "철학/논리학",
        "super_category": "인문학",
        "principle_name": "귀납법",
        "principle_name_en": "Induction",
        "ai_connection": "머신러닝 (데이터로부터의 귀납적 학습)",
        "ai_connection_en": "Machine Learning (Inductive Learning from Data)",
        "problem_solved": "개별 사례로부터 일반적 패턴과 법칙 추출",
    },
    {
        "id": "phil_occam",
        "discipline": "philosophy",
        "discipline_name": "철학/논리학",
        "super_category": "인문학",
        "principle_name": "오컴의 면도날",
        "principle_name_en": "Occam's Razor",
        "ai_connection": "모델 단순성 / 정규화 (L1/L2)",
        "ai_connection_en": "Model Simplicity / Regularization (L1/L2)",
        "problem_solved": "불필요한 복잡성을 제거하여 일반화 성능 향상",
    },
    {
        "id": "phil_epistemology",
        "discipline": "philosophy",
        "discipline_name": "철학/논리학",
        "super_category": "인문학",
        "principle_name": "인식론 (지식의 본질)",
        "principle_name_en": "Epistemology (Nature of Knowledge)",
        "ai_connection": "지식 표현 / 지식 그래프",
        "ai_connection_en": "Knowledge Representation / Knowledge Graphs",
        "problem_solved": "지식을 구조화하여 기계가 활용할 수 있는 형태로 표현",
    },
    {
        "id": "phil_ethics",
        "discipline": "philosophy",
        "discipline_name": "철학/논리학",
        "super_category": "인문학",
        "principle_name": "윤리학 (공리주의/의무론)",
        "principle_name_en": "Ethics (Utilitarianism/Deontology)",
        "ai_connection": "AI 윤리 / 책임있는 AI",
        "ai_connection_en": "AI Ethics / Responsible AI",
        "problem_solved": "AI 시스템의 도덕적 의사결정 프레임워크 설계",
    },
    {
        "id": "phil_turing_test",
        "discipline": "philosophy",
        "discipline_name": "철학/논리학",
        "super_category": "인문학",
        "principle_name": "심신문제 / 중국어 방 논증",
        "principle_name_en": "Mind-Body Problem / Chinese Room Argument",
        "ai_connection": "AI 의식/이해력 논쟁",
        "ai_connection_en": "AI Consciousness / Understanding Debate",
        "problem_solved": "기계가 진정으로 이해하는지에 대한 근본적 질문",
    },
    {
        "id": "phil_abduction",
        "discipline": "philosophy",
        "discipline_name": "철학/논리학",
        "super_category": "인문학",
        "principle_name": "가추법 (최선의 설명으로의 추론)",
        "principle_name_en": "Abduction (Inference to Best Explanation)",
        "ai_connection": "설명 가능한 AI (XAI)",
        "ai_connection_en": "Explainable AI (XAI)",
        "problem_solved": "관측된 결과에 대한 가장 그럴듯한 설명 생성",
    },
    {
        "id": "phil_modal_logic",
        "discipline": "philosophy",
        "discipline_name": "철학/논리학",
        "super_category": "인문학",
        "principle_name": "양상 논리 (가능/필연)",
        "principle_name_en": "Modal Logic (Possibility/Necessity)",
        "ai_connection": "불확실성 추론 / 가능 세계 의미론",
        "ai_connection_en": "Uncertainty Reasoning / Possible World Semantics",
        "problem_solved": "확실하지 않은 지식에 대한 형식적 추론 체계",
    },
    {
        "id": "phil_dialectics",
        "discipline": "philosophy",
        "discipline_name": "철학/논리학",
        "super_category": "인문학",
        "principle_name": "변증법 (정-반-합)",
        "principle_name_en": "Dialectics (Thesis-Antithesis-Synthesis)",
        "ai_connection": "GAN (생성자-판별자 대립)",
        "ai_connection_en": "GANs (Generator-Discriminator Opposition)",
        "problem_solved": "대립하는 두 네트워크의 경쟁을 통한 점진적 향상",
    },
    {
        "id": "phil_phenomenology",
        "discipline": "philosophy",
        "discipline_name": "철학/논리학",
        "super_category": "인문학",
        "principle_name": "현상학 (체화된 인지)",
        "principle_name_en": "Phenomenology (Embodied Cognition)",
        "ai_connection": "체화된 AI / 로봇 학습",
        "ai_connection_en": "Embodied AI / Robot Learning",
        "problem_solved": "물리적 신체와 환경 상호작용을 통한 지능 발현",
    },
]
